# Generated by Django 4.1.7 on 2026-02-15 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('admission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Admission rate in percentage', max_digits=5, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('university_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('government', 'Government')], default='private', max_length=50)),
                ('ranking', models.IntegerField(blank=True, help_text='World ranking', null=True)),
                ('ielts_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('toefl_score', models.IntegerField(blank=True, null=True)),
                ('gre_score', models.IntegerField(blank=True, null=True)),
                ('gmat_score', models.IntegerField(blank=True, null=True)),
                ('scholarships_available', models.BooleanField(default=False)),
                ('scholarships_description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'db_table': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=20)),
                ('duration_years', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('intake_months', models.CharField(blank=True, help_text='e.g., January, September', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'ordering': ['name'],
            },
        ),
    ]
