# Generated by Django 4.1.7 on 2026-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='remark',
            field=models.TextField(blank=True, help_text='Additional remarks or notes about the university'),
        ),
        migrations.AddField(
            model_name='university',
            name='uniassist_required',
            field=models.BooleanField(default=False, help_text='Whether UniAssist evaluation is required'),
        ),
    ]
