# Generated by Django 5.2.14 on 2026-05-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_remark_university_uniassist_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='academic_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='accommodation_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='additional_study_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='additional_tuition_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='application_deadline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='application_deadline_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='application_submission_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='attendance_phases_in_germany',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='beginning',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='career_services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='certificates_for_modules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='costs_of_living',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='course_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='course_organisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='current_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='daad_funding_programme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='diverse_background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='funding_available',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='funding_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='general_services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='in_cooperation_with',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='integrated_english_courses',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='integrated_german_courses',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='integrated_internships',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='international_elements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='international_support',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='language_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='languages_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='mode_of_study',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='other_international_elements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='pace_of_course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='part_time_employment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='portal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='program',
            name='program_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='program',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='semester_contribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='special_funding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='study_abroad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='study_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='supervisor_student_ratio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='teaching_language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='technical_equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='intake_months',
            field=models.CharField(blank=True, help_text='e.g., January, September', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
