# Generated by Django 5.2.14 on 2026-06-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag or short code', max_length=10)),
                ('group', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_score', models.IntegerField(default=5, help_text='Points for predicting exact score')),
                ('correct_winner', models.IntegerField(default=3, help_text='Points for predicting correct winner or draw')),
                ('correct_goal_difference', models.IntegerField(default=2, help_text='Points for predicting correct goal difference (excluding exact score)')),
                ('tournament_winner', models.IntegerField(default=10, help_text='Points for predicting tournament winner')),
                ('tournament_runner_up', models.IntegerField(default=5, help_text='Points for predicting runner-up')),
                ('tournament_predictions_locked', models.BooleanField(default=False, help_text='Lock tournament winner/runner-up predictions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Configuration',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('stage', models.CharField(choices=[('group', 'Group Stage'), ('r16', 'Round of 16'), ('qf', 'Quarter Final'), ('sf', 'Semi Final'), ('3rd', '3rd Place Play-off'), ('final', 'Final')], default='group', max_length=10)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('match_number', models.PositiveIntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='wc_predictor.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='wc_predictor.team')),
            ],
            options={
                'ordering': ['match_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_predictions', to='wc_predictor.team')),
                ('predicted_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_predictions', to='wc_predictor.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wc_tournament_prediction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_runner_ups', to='wc_predictor.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to='wc_predictor.team')),
            ],
            options={
                'verbose_name': 'Tournament Result',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('points_earned', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='wc_predictor.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
